Repository MicroClub-USTHB/Hacktoberfest-2k20, pull requests merged in 2020-10, with the labels that each got.

#1 Create Anis-Adlaoui_FootballerCat.png
  myOctocat/Anis-Adlaoui_FootballerCat.png
Labels: Hacktoberfest, good first issue

#2 Added the contributor.md, myoctocat design and a e-commerce-template-website personal project
  contributors/Ouassim_kessir.md
  myOctocat/wassim201_octastronaut.png
  projects/e-commerce-template-website/.gitignore
  projects/e-commerce-template-website/README.md
  projects/e-commerce-template-website/config/auth.js
  projects/e-commerce-template-website/config/passport.js
  projects/e-commerce-template-website/css/style.css
  projects/e-commerce-template-website/index.js
  projects/e-commerce-template-website/models/Item.js
  projects/e-commerce-template-website/models/User.js
  projects/e-commerce-template-website/routes/index.js
  projects/e-commerce-template-website/routes/users.js
  projects/e-commerce-template-website/views/addproduct.ejs
  projects/e-commerce-template-website/views/homepage.ejs
  projects/e-commerce-template-website/views/item.ejs
  projects/e-commerce-template-website/views/layout.ejs
  projects/e-commerce-template-website/views/login.ejs
  projects/e-commerce-template-website/views/register.ejs
Labels: Hacktoberfest, good first issue

#3 added Marouane_Bouaricha.md + Project
  contributors/Marouane_Bouaricha.md
  projects/portScanner/README.md
  projects/portScanner/cmd/main.go
  projects/portScanner/go.mod
  projects/portScanner/go.sum
  projects/portScanner/port/port.go
Labels: Hacktoberfest

#15 Update README.md
  README.md
  translations/README_Fr.md
Labels: documentation :page_with_curl:, enhancement, hacktoberfest-accepted

#18 added my infos
  contributors/HARKAT_ADEL_LARBI.md
Labels: Hacktoberfest, hacktoberfest-accepted

#20 weather app resolve issue #8
  projects/weather-app/README.md
  projects/weather-app/index.css
  projects/weather-app/index.html
  projects/weather-app/index.js
Labels: Hacktoberfest, hacktoberfest-accepted

#23 added UDP-RMI
  projects/UDP-RMI/.classpath
  projects/UDP-RMI/.project
  projects/UDP-RMI/.settings/org.eclipse.jdt.core.prefs
  projects/UDP-RMI/bin/IP1.class
  projects/UDP-RMI/bin/c1.class
  projects/UDP-RMI/bin/c2.class
  projects/UDP-RMI/bin/c3.class
  projects/UDP-RMI/bin/c4.class
  projects/UDP-RMI/bin/c5.class
  projects/UDP-RMI/readme.md
  projects/UDP-RMI/src/IP1.java
  projects/UDP-RMI/src/c1.java
  projects/UDP-RMI/src/c2.java
  projects/UDP-RMI/src/c3.java
  projects/UDP-RMI/src/c4.java
  projects/UDP-RMI/src/c5.java
Labels: Hacktoberfest

#24 added tcp_udp
  projects/UDP-TCP/.classpath
  projects/UDP-TCP/.project
  projects/UDP-TCP/.settings/org.eclipse.jdt.core.prefs
  projects/UDP-TCP/.settings/org.jboss.ide.eclipse.as.core.prefs
  projects/UDP-TCP/README.md
  projects/UDP-TCP/bin/IP4.class
  projects/UDP-TCP/bin/p1.class
  projects/UDP-TCP/bin/p2.class
  projects/UDP-TCP/bin/p3.class
  projects/UDP-TCP/bin/p4.class
  projects/UDP-TCP/src/IP4.java
  projects/UDP-TCP/src/p1.java
  projects/UDP-TCP/src/p2.java
  projects/UDP-TCP/src/p3.java
  projects/UDP-TCP/src/p4.java
Labels: Hacktoberfest, hacktoberfest-accepted

#25 TCP-UDP-RMI
  projects/rmi-tcp-udp/.classpath
  projects/rmi-tcp-udp/.project
  projects/rmi-tcp-udp/.settings/org.eclipse.jdt.core.prefs
  projects/rmi-tcp-udp/.settings/org.jboss.ide.eclipse.as.core.prefs
  projects/rmi-tcp-udp/bin/P1.class
  projects/rmi-tcp-udp/bin/P2.class
  projects/rmi-tcp-udp/bin/P3.class
  projects/rmi-tcp-udp/bin/P4.class
  projects/rmi-tcp-udp/bin/RMI.class
  projects/rmi-tcp-udp/readme.md
  projects/rmi-tcp-udp/src/P1.java
  projects/rmi-tcp-udp/src/P2.java
  projects/rmi-tcp-udp/src/P3.java
  projects/rmi-tcp-udp/src/P4.java
  projects/rmi-tcp-udp/src/RMI.java
Labels: Hacktoberfest

#30 added my octocat
  contributors/bouzi.md
  myOctocat/bouzi_myoctocat.png
Labels: Hacktoberfest, hacktoberfest-accepted

#31 updated contributer file
  contributors/bouzi.md
Labels: Hacktoberfest, hacktoberfest-accepted

#33 I added Ikram Belkhiri profile file
  contributors/Ikram-Belkhiri.md
Labels: Hacktoberfest, good first issue :beginner:

#32 Scraping algiers townships using beautifulsoup and creating folium marked map
  myOctocat/octocat.png
  projects/Scraping_townships_of_ALgiers_and_creating_a_folium_marked_map.ipynb
Labels: Hacktoberfest, hacktoberfest-accepted

#35 Scraping.md
  projects/Scraping
  projects/Scraping townships of ALgiers and creating a folium marked map.ipynb
Labels: Hacktoberfest

#37 Clustering venues
  projects/Comparing two cities based on venues.ipynb
Labels: Hacktoberfest, hacktoberfest-accepted

#38 Start a business in Algiers
  Best Place to start a business in ALGIERS.ipynb
  Clustering_Algiers_venues.ipynb
Labels: Hacktoberfest, hacktoberfest-accepted

#41 matlab matrix basics
  projects/matlab matrix basics/matlab101.m
Labels: Hacktoberfest, hacktoberfest-accepted

#34 Added my profile
  contributors/Ahmed_I_MOKHTARI.md
Labels: Hacktoberfest, hacktoberfest-accepted

#39 Create YALAManel.md
  contributors/YALAManel.md
Labels: Hacktoberfest, hacktoberfest-accepted

#43 added a classification algorithm, Fuzzy C-means to be more specific
  projects/Algorithms/classification/Fuzzy_C_Means.py
Labels: Hacktoberfest, hacktoberfest-accepted

#44 Baby Yoda webmap project cocntribution
  projects/Baby Yoda Web Map/BabyYodaSprite.gif
  projects/Baby Yoda Web Map/README.md
  projects/Baby Yoda Web Map/yoda.py
Labels: Hacktoberfest, hacktoberfest-accepted

#45 user card web project addition
  projects/User Card - web/README.md
  projects/User Card - web/index.html
  projects/User Card - web/style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#46 Fantasy Adventure Text Game
  projects/Text Adventure Fantasy Game/README.md
  projects/Text Adventure Fantasy Game/adventure.py
Labels: Hacktoberfest, hacktoberfest-accepted

#47 Contribution to HacktoberFest
  Data_vis_w_plt/Data_Representation_w_matplotlib.ipynb
  Data_vis_w_plt/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#48 More data vis on worldwide Covid case
  Data_vis_w_plt/Data_vis_on_time_series.ipynb
Labels: Hacktoberfest, hacktoberfest-accepted

#49 Adding a intro level ML prediciton notebook with sckitilearn
  scikit_predictions/README.md
  scikit_predictions/flight_delay_prediction_w_Scikitlearn.ipynb
Labels: Hacktoberfest, hacktoberfest-accepted

#50 Fixing the misplacement of the code in the repo
  projects/Data_vis_w_plt/ Data_Representation_w_matplotlib.ipynb
  projects/Data_vis_w_plt/ Data_vis_on_time_series.ipynb
  projects/Data_vis_w_plt/README.md
  projects/Scikit_predictions/README.md
  projects/Scikit_predictions/flight_delay_prediction_w_Scikitlearn.ipynb
Labels: Hacktoberfest, hacktoberfest-accepted

#52 Micro Notes
  .gitignore
  projects/Micro Note/app.js
  projects/Micro Note/middlewares/login.js
  projects/Micro Note/modules/note.js
  projects/Micro Note/modules/user.js
  projects/Micro Note/package-lock.json
  projects/Micro Note/package.json
  projects/Micro Note/public/Login.html
  projects/Micro Note/public/Note.html
  projects/Micro Note/public/Notes.html
  projects/Micro Note/public/css/bootstrap-grid.css
  projects/Micro Note/public/css/bootstrap-grid.css.map
  projects/Micro Note/public/css/bootstrap-grid.min.css
  projects/Micro Note/public/css/bootstrap-grid.min.css.map
  projects/Micro Note/public/css/bootstrap-reboot.css
  projects/Micro Note/public/css/bootstrap-reboot.css.map
  projects/Micro Note/public/css/bootstrap-reboot.min.css
  projects/Micro Note/public/css/bootstrap-reboot.min.css.map
  projects/Micro Note/public/css/bootstrap.css
  projects/Micro Note/public/css/bootstrap.css.map
  projects/Micro Note/public/css/bootstrap.min.css
  projects/Micro Note/public/css/bootstrap.min.css.map
  projects/Micro Note/public/css/style.css
  projects/Micro Note/public/img/avatar1.png
  projects/Micro Note/public/img/avatar2.jpg
  projects/Micro Note/public/img/basket.svg
  projects/Micro Note/public/index.html
  projects/Micro Note/public/js/bootstrap.bundle.js
  projects/Micro Note/public/js/bootstrap.bundle.js.map
  projects/Micro Note/public/js/bootstrap.bundle.min.js
  projects/Micro Note/public/js/bootstrap.bundle.min.js.map
  projects/Micro Note/public/js/bootstrap.js
  projects/Micro Note/public/js/bootstrap.js.map
  projects/Micro Note/public/js/bootstrap.min.js
  projects/Micro Note/public/js/bootstrap.min.js.map
  projects/Micro Note/public/js/jquery-3.5.1.min.js
  projects/Micro Note/public/js/script.js
  projects/Micro Note/routes/index.js
  projects/Micro Note/routes/notes.js
  projects/Micro Note/routes/user.js
  projects/Micro Note/stuff to add.txt
  projects/Micro Note/views/Login.ejs
  projects/Micro Note/views/Notes.ejs
  projects/Micro Note/views/createNote.ejs
  projects/Micro Note/views/editNote.ejs
  projects/Micro Note/views/index.ejs
  projects/Micro Note/views/navbar.ejs
  projects/Micro Note/views/signup.ejs
Labels: Hacktoberfest, hacktoberfest-accepted

#51 Sharing my octocat
  myOctocat/LAKSACI_Sarra_killer_next_door.png
Labels: Hacktoberfest, hacktoberfest-accepted

#53 upadte of my profile
  contributors/Debbah_Mehdi_Sofiane.md
Labels: Hacktoberfest, hacktoberfest-accepted

#55 Update README.md with Hackotberfest badge
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#58 Docs enhancement
  README.md
  docs/index.html
  projects/TCP-RMI/readme.md
  projects/UDP-RMI/readme.md
  projects/UDP-TCP/README.md
Labels: Hacktoberfest, documentation :page_with_curl:, enhancement
